<?php

namespace Zeega\DataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SequenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SequenceRepository extends EntityRepository
{
}
